---
- name: get secrets with ssm paramter store
  set_fact:
    initpass:
      secret: "{{ lookup('aws_ssm', 'PARAMETERSTOREPATH') }}"

- name: 'output secrets'
  debug: var="{{ item }}"
  with_items:
    - "initpass.secret"
    - "initpass.not_exist"

- name: Create an arcgis user
  win_user:
    name: "{{ arcgis_service_account }}"
    password: "{{ initpass.secret }}"
    user_cannot_change_password: yes
    password_never_expires: yes
    update_password: on_create

- name: overwrite agent_sa password variable
  set_fact:
    arcgis_service_account_pw: "{{ initpass.secret }}"