---
- name: deploy arcgis portal
  hosts: all
  become: false
  roles:
    - general
    - common
    - arcgisportal
  vars_files:
    - vars_arcgisportal.yaml
  # vars:
  #     ansible_python_interpreter: c:\Python39\bin