---
# trailing / or \ is not used basically

# common vars
arcgis_version: VERSION YOU WANT TO INSTALL(ie. 10.9.1, 11.0. This is used in extract directory)
arcgis_service_account_group: ARCGIS SERVICE ACCOUNT GROUP FOR LINUX
arcgis_service_account: ARCGIS SERVICE ACCOUNT
arcgis_service_account_pw: ARCGIS SERVICE ACCOUNT ENCRYPTED PASSWORD
arcgisports:
  - 2443
  - 9876
  - 29080
  - 29081
installer_bucket_name: YOUR BUCKET NAME HOSTING INSTALLERS
logs_bucket_name: YOUR BUCKET NAME for LOGS

# for Windows
win_arcgis_component: ArcGISDataStore
win_product_id: '{CHECK SOFTWARE PRODUCTCODE}'
# product_id is listed here: https://support.esri.com/en/Technical-Article/000013200
win_remote_temp_dest_dir: FOR COPY-DESTINATEION DIRECCTORY
win_remote_extract_dest_dir: FOR EXTRACTION OF INSTALLERS DIRECTORY

win_copy_local_files: # for Local machines. Use the win_copy_s3_files variables for aws.
  - ARCGIS DATA STORE INSTALLER FILE PATH
win_copy_s3_files:
  - ARCGIS DATA STORE INSTALLER

win_install_dir: INSTALL DIRECTORY
win_datastore_dir: CONTENT DIRECTORY
win_install_log_dir: INSTALLATION LOG DIRECTORY
win_install_log_path: "{{ win_install_log_dir }}\\arcgis-datastore.log"

win_setup_msi_path: "{{ win_remote_extract_dest_dir }}\\ArcGIS {{ arcgis_version }}\\{{ win_arcgis_component }}\\SetupFiles\\setup.msi"
win_setup_msi_with_log_arguments: "/qn ACCEPTEULA{{'='}}yes INSTALLDIR{{'='}}{{ win_install_dir }} USER_NAME{{'='}}{{ arcgis_service_account }} PASSWORD{{'='}}{{ arcgis_service_account_pw }} /L*V {{ win_install_log_path }}"
win_setup_msi_argumentlist: "/i \"\"{{ win_setup_msi_path }}\"\" {{ win_setup_msi_with_log_arguments }}"
win_setup_msi_process_command: "Start-Process 'msiexec' -ArgumentList \"{{ win_setup_msi_argumentlist }}\" -Wait" 
# service name parameter
win_service_name: "ArcGIS Data Store"


# for Linux
remote_temp_dest_dir: /tmp/arcgis
remote_extract_dest_dir: "/home/{{ arcgis_service_account }}/setup"
hostname: testnode
installer_bucket_name: egihs-arcgis-installer
logs_bucket_name: egihs-goldenimage-logs

copy_s3_files:
  - ARCGIS DATA STORE INSTALLER FILE
copy_local_files:
  - ARCGIS DATA STORE INSTALLER FILE PATH
copy_s3_files:
  - ArcGIS_DataStore_Linux_1091_180204.tar.gz
install_dir: INSTALL DIRECTORY
site_admin_user: siteadmin
site_admin_user_pw: P@ssw0rd!!!
# each arcgis components
setup_command: "./Setup -m silent --verbose -l yes -d {{ install_dir }}"
setup_command_location: "{{ remote_extract_dest_dir }}/ArcGISDataStore_Linux/"
manual_start_shell: "./startdatastore.sh"
manual_start_shell_location: "{{ install_dir }}/arcgis/datastore/"
service_unit_path: "{{ install_dir }}/arcgis/datastore/framework/etc/scripts/arcgisdatastore.service"
service_unit_dest_path: /etc/systemd/system/arcgisdatastore.service
# handler paramter
service_name: arcgisdatastore